name: Build and save Docker images

on:
  release:
    types: [published]

env:
  IC_COMMIT: b9a0f18dd5d6019e3241f205de797bca0d9cc3f8

jobs:
  build-and-upload-ic-prep:
    name: Build ic-prep image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and save Docker image
        run: |
          cd ic-prep
          docker build -t ic-prep --build-arg IC_COMMIT=$IC_COMMIT .
          docker save ic-prep > ../ic-prep.tar

      - name: Compress Docker image
        run: gzip ic-prep.tar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
              ic-prep.tar.gz

  build-and-upload-gateway:
    name: Build gateway image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and save Docker image
        run: |
          cd gateway
          docker build -t gateway --build-arg IC_COMMIT=cf0a12b7b3971b204d06efc65690b23e58b8c481 . 
          docker save gateway > ../gateway.tar

      - name: Compress Docker image
        run: gzip gateway.tar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
              gateway.tar.gz

  build-and-upload-upgrader:
    name: Build upgrader image and demo_cfg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and save inner node image
        run: |
          cd node
          docker build -t node-container --build-arg IC_COMMIT=$IC_COMMIT .
          docker save node-container > ../upgrader/node.tar

      - name: Build and save Docker image
        run: |
          cd upgrader
          docker build -t upgrader --build-arg IC_COMMIT=$IC_COMMIT .
          docker save upgrader > ../upgrader.tar

      - name: Compress Docker image
        run: gzip upgrader.tar
      
      - name: Write upgrader sha256sum to file
        run: sha256sum upgrader.tar.gz | cut -d ' ' -f 1 > upgrader-sha256sum.txt

      - name: Write IC_COMMIT to file
        run: echo $IC_COMMIT > ic-commit.txt

      - name: Gzip demo configuration
        run: tar -czvf demo_cfg.tar.gz demo_cfg 

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
              upgrader.tar.gz
              demo_cfg.tar.gz
              upgrader-sha256sum.txt
              ic-commit.txt
