name: Build and save Docker images

on:
  release:
    types: [published]

jobs:
  build-and-upload-ic-prep:
    name: Build and upload ic-prep image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and save Docker image
        run: |
          cd ic-prep
          docker build -t ic-prep .
          docker save ic-prep > ../ic-prep.tar

      - name: Compress Docker image
        run: gzip ic-prep.tar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
              ic-prep.tar.gz

  build-and-upload-upgrader:
    name: Build and upload upgrader image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and save inner node image
        run: |
          cd node
          docker build -t node-container .
          docker save node-container > ../upgrader/node.tar

      - name: Build and save Docker image
        run: |
          cd upgrader
          docker build -t upgrader .
          docker save upgrader > ../upgrader.tar

      - name: Compress Docker image
        run: gzip upgrader.tar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
              upgrader.tar.gz
